### ISSUE TITLE
Margin issue

### ISSUE THREAD

**Issue by faithebert** [faithebert/responsive-section#1]
I am all done the most recent coding exercise, all my screenshots are matching, the only issue is Markbot is needing a different margin on the .wrapper tag, I have tried auto, 0, 1.4rem as stated in the instructions, and multiple other values and it has the same error for each. Thanks 

@thomasjbradley

<img width="869" alt="Screenshot 2019-11-21 20 21 47" src="https://user-images.githubusercontent.com/55109632/69390251-9c018c00-0c9c-11ea-80a6-825eaab2a4dc.png">
<img width="792" alt="Screenshot 2019-11-21 20 21 10" src="https://user-images.githubusercontent.com/55109632/69390252-9c018c00-0c9c-11ea-9eb0-3b33694d3ac8.png">

**Comment by thomasjbradley** [comment]
Have you tried `0 auto`?

**Comment by faithebert** [comment]
Got it, thanks!
